spring:
  main:
    allow-circular-references: true
  datasource:
    username: ENC(sm3Avk0/y0wqBI7KXMIyx5wJX9Y+vR2LvREJScc7KtcJ4ZHBOnDLvw1mhbxcbIJR)
    password: ENC(VCNbMChTp2K9pBJRXF9RnzNpCTeJ/DjeX45PqsLPvgG2E9VkBvdM/1qPkhORbnbZ)
    url: jdbc:mysql://43.138.201.19/imrms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 43.138.201.19
      port: 6379
      password: ENC(/ZaLefZkSkCQ2fqFNq7pA67qumt0vn4BiX8tKg3LTHUs5z0TKPVW+vUFo046Gf7Y+of8a2QpgfIA0RoBjuPswA==)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: sk1477264431@163.com
    password: ENC(qPmtrZXuOPiADhFO4BreC6yGLeCa1O4Y4TuHOEbrLSsYb2/+KKnPoRbdUhQh165ERxntl0px9EQ8aUTL+np+1Q==)
    default-encoding: utf-8
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.simpl.RAMJobStore

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: false

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson2
  remote:
    default:
      type: redis
      keyConvertor: fastjson2
      broadcastChannel: projectA
      valueEncoder: kryo5
      valueDecoder: kryo5
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}

logging:
  level:
    com.imrms.com.imrms.intelligent_meeting_room: INFO

BaiduAip:
  appId: ENC(2IoCyGnxO2OqNuAKCsW/JwCVmOqZNAtYx/qqKzWIV+EdfLqn7aReli2SpFxQqNX0)
  apiKey: ENC(WOdujdaYBMVIkFXdShlCjMxQdtlxZ/nD+ttPhWKG4M8FP5iJ/jyRZb7fTQuiyedZy7h+yrzfz6jA9UxAEHZ8EQ==)
  secretKey: ENC(sjeAIiu+VYoz//q9oqFz95Z0rcIiSXTRK5GBcwm2cOsH7aEO2RgNtnEpo+3xJWFficGxSU7cIaT1ns4vIB4K2G1ktaoTcVJ68SqXUub4vl8=)

mail:
  fromMail:
    fromAddress: sk1477264431@163.coom